@extends('pdf.layouts.export-document')

@section('title', 'Forecast - ' . $bulanAktif . ' ' . $tahun)
@section('form-title', 'SALES FORECAST & STOCK ESTIMATION')
@section('page-orientation', 'landscape')

@section('subtitle')
    Periode {{ $monthTranslations[$bulanAktif] ?? $bulanAktif }} {{ $tahun }} | Reference {{ $activeRefMonths }} months ({{ implode(', ', array_map(fn($b) => $monthTranslations[$b] ?? $b, $tigaBulanTerakhir)) }}) | Forecast +{{ rtrim(rtrim(number_format($activePercentage, 2, '.', ''), '0'), '.') }}% | Target DOI {{ $activeDoi }} days
@endsection

@section('meta')
    <table>
        <tr>
            <td style="width: 25%; font-weight: bold;">Tanggal Cetak</td>
            <td style="width: 2%;">:</td>
            <td style="width: 30%;">{{ \Carbon\Carbon::now()->translatedFormat('d F Y, H:i') }} WIB</td>
            <td style="width: 20%; font-weight: bold; text-align: right;">End Stock as of</td>
            <td style="width: 2%;">:</td>
            <td style="width: 21%;">{{ $teksStokAkhir }} {{ $tahun }}</td>
        </tr>
        <tr>
            <td style="font-weight: bold;">Total Produk</td>
            <td>:</td>
            <td>{{ count($stockForecast) }} items</td>
            <td style="font-weight: bold; text-align: right;">Generated by</td>
            <td>:</td>
            <td>{{ Auth::user()->name ?? 'System' }}</td>
        </tr>
    </table>
@endsection

@section('extra-style')
    table.export-table th { font-size: 7pt; padding: 3px 2px; }
    table.export-table td { font-size: 7pt; padding: 2px 3px; }
    .legend-box { font-size: 6pt; background: #f8fafc; border: 1px solid #e2e8f0; padding: 5px 7px; margin-top: 8px; line-height: 1.4; }
@endsection

@section('content')
<table class="export-table">
    <thead>
        <tr>
            <th style="width: 4%;">No</th>
            <th style="width: 22%;">Product Name</th>
            <th style="width: 22%;">Monthly Qty<br><span style="font-weight: normal; font-size: 6pt;">Last {{ $activeRefMonths }} months (3 / row)</span></th>
            <th>Total</th>
            <th>Average<br><span style="font-weight: normal; font-size: 6pt;">/month</span></th>
            <th style="background-color: #1e40af !important;">Forecast<br><span style="font-weight: normal; font-size: 6pt;">+{{ rtrim(rtrim(number_format($activePercentage, 2, '.', ''), '0'), '.') }}%</span></th>
            <th>Buffer<br><span style="font-weight: normal; font-size: 6pt;">DOI {{ $activeDoi }}d</span></th>
            <th>End Stock<br><span style="font-weight: normal; font-size: 6pt;">{{ $teksStokAkhir }}</span></th>
            <th>DOI<br><span style="font-weight: normal; font-size: 6pt;">days</span></th>
            <th>MOQ</th>
            <th style="background-color: #3730a3 !important;">Order</th>
        </tr>
    </thead>
    <tbody>
        @forelse($stockForecast as $i => $item)
            <tr>
                <td>{{ $i + 1 }}</td>
                <td style="text-align: left; font-weight: bold;">{{ $item['nama_produk'] }}</td>
                <td style="padding: 2px; background-color: #f8fafc;">
                    <table style="width: 100%; border-collapse: collapse; table-layout: fixed; border: 1px solid #94a3b8;">
                        @foreach(array_chunk($tigaBulanTerakhir, 3) as $chunk)
                            <tr>
                                @foreach($chunk as $bulan)
                                    <td style="border: 1px solid #94a3b8; text-align: center; padding: 2px 1px; background-color: #ffffff;">
                                        <span style="font-weight: bold; color: #1e40af; font-size: 6pt;">{{ strtoupper(substr($monthTranslations[$bulan] ?? $bulan, 0, 3)) }}</span><br>
                                        <span style="font-size: 7pt; color: #1e293b;">{{ number_format($item['detail_bulan'][$bulan] ?? 0, 0, ',', '.') }}</span>
                                    </td>
                                @endforeach
                                @for($k = count($chunk); $k < 3; $k++)
                                    <td style="border: 1px solid #e2e8f0; background-color: #f8fafc;"></td>
                                @endfor
                            </tr>
                        @endforeach
                    </table>
                </td>
                <td style="font-weight: bold; background-color: #f8fafc;">{{ number_format($item['total_qty'], 0, ',', '.') }}</td>
                <td style="background-color: #f1f5f9;">{{ number_format($item['avg_qty'], 2, ',', '.') }}</td>
                <td style="font-weight: bold; color: #1e40af; background-color: #eff6ff;">{{ number_format($item['forecast_qty'], 0, ',', '.') }}</td>
                <td style="background-color: #fffbeb;">{{ number_format($item['buffer_qty'], 0, ',', '.') }}</td>
                <td style="background-color: #fff7ed;">{{ number_format($item['stok_tersedia'], 0, ',', '.') }}</td>
                <td style="background-color: #fff1f2;">{{ number_format($item['doi_qty'], 0, ',', '.') }}</td>
                <td>{{ number_format($item['moq'], 0, ',', '.') }}</td>
                <td style="font-weight: bold; color: #3730a3; background-color: #eef2ff;">{{ number_format($item['order_qty'], 0, ',', '.') }}</td>
            </tr>
        @empty
            <tr>
                <td colspan="11" style="text-align: center; padding: 10px; color: #64748b;">No forecast data available for the selected period.</td>
            </tr>
        @endforelse
    </tbody>
</table>

<div style="margin-top: 8px; font-size: 7pt; font-weight: bold; color: #1e293b;">Contribution per Product (PS Breakdown)</div>
<table class="export-table">
    <thead>
        <tr>
            <th style="width: 6%;">No</th>
            <th>Product Name</th>
            <th style="width: 22%;">Contributor</th>
            <th style="width: 14%;">Qty</th>
            <th style="width: 14%;">Share</th>
        </tr>
    </thead>
    <tbody>
        @forelse($stockForecast as $i => $item)
            @php $psCount = count($item['ps_breakdown']); @endphp
            @forelse($item['ps_breakdown'] as $ps => $qty)
                <tr>
                    @if($loop->first)
                        <td rowspan="{{ $psCount }}" style="vertical-align: middle;">{{ $i + 1 }}</td>
                        <td rowspan="{{ $psCount }}" style="text-align: left; vertical-align: middle; font-weight: bold;">{{ $item['nama_produk'] }}</td>
                    @endif
                    <td>{{ explode(' ', trim($ps))[0] }}</td>
                    <td>{{ number_format($qty, 0, ',', '.') }} {{ $item['satuan_sales'] }}</td>
                    <td>{{ $item['total_qty'] > 0 ? number_format($qty / $item['total_qty'] * 100, 1, ',', '.') : '0,0' }}%</td>
                </tr>
            @empty
                <tr>
                    <td>{{ $i + 1 }}</td>
                    <td style="text-align: left;">{{ $item['nama_produk'] }}</td>
                    <td colspan="3" style="color: #64748b;">No contributor data</td>
                </tr>
            @endforelse
        @empty
            <tr>
                <td colspan="5" style="text-align: center; padding: 8px; color: #64748b;">No data</td>
            </tr>
        @endforelse
    </tbody>
</table>

<div class="legend-box">
    <b>How to read:</b> &nbsp;
    <b>Average</b> = Total / {{ $activeRefMonths }} &nbsp;|&nbsp;
    <b>Forecast</b> = Average + {{ rtrim(rtrim(number_format($activePercentage, 2, '.', ''), '0'), '.') }}% &nbsp;|&nbsp;
    <b>Buffer</b> = Average x ({{ $activeDoi }}/30) &nbsp;|&nbsp;
    <b>DOI</b> = (End Stock / Average) x 30 &nbsp;|&nbsp;
    <b>Order</b> = IF((End Stock - Forecast) &lt; Buffer) THEN CEILING(Buffer - (End Stock - Forecast), MOQ) ELSE 0
    @php $ex = $stockForecast[0] ?? null; @endphp
    @if($ex)
        <br><span style="color: #1e40af;">Example ({{ \Illuminate\Support\Str::limit($ex['nama_produk'], 35) }}): Total {{ number_format($ex['total_qty'],0,',','.') }} / {{ $activeRefMonths }} = {{ number_format($ex['avg_qty'],2,',','.') }} | Forecast {{ number_format($ex['forecast_qty'],0,',','.') }} | Buffer {{ number_format($ex['buffer_qty'],0,',','.') }} | DOI {{ number_format($ex['doi_qty'],0,',','.') }}d | Order {{ number_format($ex['order_qty'],0,',','.') }}</span>
    @endif
</div>
@endsection

@section('footer-note')
    Forecast {{ $bulanAktif }} {{ $tahun }} | {{ count($stockForecast) }} products
@endsection
